<?php

$classes = array(
            'MainIndex'                     => '../services/index.php',
            'MainAdmin'                     => '../services/admin.php',
            //API PUBLIC
            'Mailjet'                       => '../api/mailjet/php-mailjet.class-mailjet-0.1.php',
            'PHPMailer'                     => '../api/phpmailer/class.phpmailer.php',
            //UTILS
            'AppLog'                        => '../utils/AppLog.class.php',
            'LoadConfig'                    => '../utils/loadConfig.php',
            'NotFoundException'             => '../exception/NotFoundException.php',
            'TextStatic'                    => '../utils/TextStatic.php',
            'Redirect'                      => '../utils/redirect.php',
            'imageTreatment'                => '../utils/imageTreatment.php',
            'DownloadBinaryFile'            => '../utils/DownloadBinaryFile.class.php',
            'FormValidation'                => '../utils/FormValidation.class.php',
            'SecurityUtil'                  => '../utils/SecurityUtil.class.php',
            'UtilSession'                   => '../utils/UtilSession.class.php',
            'UtilMail'                      => '../utils/UtilMail.class.php',
            'UtilNavigateur'                => '../utils/UtilNavigateur.class.php',
            'Util'                          => '../utils/Util.class.php',
            //OBJETS BUSINESS            
            'Lieu'                          => '../model/Lieu.class.php',
            'Evenement'                     => '../model/Evenement.class.php',
            'Theme'                         => '../model/Theme.class.php',
            'Communaute'                    => '../model/Communaute.class.php',
            'Intervenant'                   => '../model/Intervenant.class.php',
            'Type'                          => '../model/Type.class.php',
            'User'                          => '../model/User.class.php',
            'Administrateur'                => '../model/Administrateur.class.php',
            'TypeEvenement'                 => '../model/TypeEvenement.class.php',
            'Slide'                         => '../model/Slide.class.php',
            'Place'                         => '../model/Place.class.php',
            //DAO
            'Db'                            => '../dao/Db.class.php',
            'CacheDao'                      => '../dao/CacheDao.class.php',
            'UtilsDao'                      => '../dao/UtilsDao.class.php', 
            //DAO-ACTION  
            'CommunauteActionDao'           => '../dao/action/CommunauteActionDao.class.php',
            'IntervenantActionDao'          => '../dao/action/IntervenantActionDao.class.php',
            'EvenementActionDao'            => '../dao/action/EvenementActionDao.class.php',
            'LieuActionDao'                 => '../dao/action/LieuActionDao.class.php',
            'TypeActionDao'                 => '../dao/action/TypeActionDao.class.php',
            'ThemeActionDao'                => '../dao/action/ThemeActionDao.class.php',
            'AdministrateurActionDao'       => '../dao/action/AdministrateurActionDao.class.php',
            'UserActionDao'                 => '../dao/action/UsersActionDao.class.php',   
            'NewsletterActionDao'           => '../dao/action/NewsletterActionDao.class.php',  
            'GeolocalisationActionDao'      => '../dao/action/GeolocalisationActionDao.class.php', 
            'TypeEvenementActionDao'        => '../dao/action/TypeEvenementActionDao.class.php', 
            'DiaporamaActionDao'            => '../dao/action/DiaporamaActionDao.class.php', 
            'MenuActionDao'                 => '../dao/action/MenuActionDao.class.php',  
            //DAO-QUERY
            'AdministrateurQueryDao'        => '../dao/query/AdministrateurQueryDao.class.php',
            'CommunauteQueryDao'            => '../dao/query/CommunauteQueryDao.class.php',
            'IntervenantQueryDao'           => '../dao/query/IntervenantQueryDao.class.php',
            'EvenementQueryDao'              => '../dao/query/EvenementQueryDao.class.php',
            'LieuQueryDao'                  => '../dao/query/LieuQueryDao.class.php', 
            'TypeQueryDao'                  => '../dao/query/TypeQueryDao.class.php',
            'ThemeQueryDao'                 => '../dao/query/ThemeQueryDao.class.php',
            'UserQueryDao'                  => '../dao/query/UsersQueryDao.class.php',   
            'NewsletterQueryDao'            => '../dao/query/NewsletterQueryDao.class.php',
            'GeolocQueryDao'                => '../dao/query/GeolocQueryDao.class.php',
            'TypeEvenementQuery'            => '../dao/query/TypeEvenementQuery.class.php',
            'DiaporamaQueryDao'             => '../dao/query/DiaporamaQueryDao.class.php',
            'MenuQueryDao'                  => '../dao/query/MenuQueryDao.class.php', 
            //SERVICES
            'ThemeAction'                   => '../services/ThemeAction.class.php',
            'CommunauteAction'              => '../services/CommunauteAction.class.php',
            'LieuAction'                    => '../services/LieuAction.class.php',
            'EvenementAction'               => '../services/EvenementAction.class.php',
            'TypeAction'                    => '../services/TypeAction.class.php',
            'IntervenantAction'             => '../services/IntervenantAction.class.php',
            'UserAction'                    => '../services/UserAction.class.php',
            'AdministrateurAction'          => '../services/AdministrateurAction.class.php',
            'MenuAction'                    => '../services/MenuAction.class.php',
            'TypeEvenementAction'           => '../services/TypeEvenementAction.class.php',
            'AjaxAction'                    => '../services/AjaxAction.class.php',
            'GeoLocalisation'               => '../services/GeoLocalisation.class.php',
            'DiaporamaAction'               => '../services/DiaporamaAction.class.php',
            'NewsletterAction'              => '../services/NewsletterAction.class.php',
            'OrganisateurAnalyse'           => '../services/OrganisateurAnalyse.class.php',
            //OUTILS DE RECHERCHE
            'EvenementSearchCriteria'       => '../services/EvenementSearchCriteria.class.php',
            'OrganisateurSearchCriteria'    => '../services/OrganisateurSearchCriteria.class.php',
            //IHM
            'HtmlFormComponents'            => '../services/HtmlFormComponents.class.php',
            'HtmlGuiComponent'              => '../services/HtmlGuiComponent.class.php',
            'HtmlUtilComponents'            => '../services/HtmlUtilComponents.class.php'    
        );
?>
